// Shared Tailwind config — loaded BEFORE cdn.tailwindcss.com in every page
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface":                  "#131318",
        "surface-dim":              "#131318",
        "surface-bright":           "#39383e",
        "surface-container-lowest": "#0e0e13",
        "surface-container-low":    "#1b1b20",
        "surface-container":        "#1f1f25",
        "surface-container-high":   "#2a292f",
        "surface-container-highest":"#35343a",
        "surface-tint":             "#00dbe9",
        "background":               "#131318",
        "on-background":            "#e4e1e9",
        "on-surface":               "#e4e1e9",
        "on-surface-variant":       "#b9cacb",
        "outline":                  "#849495",
        "outline-variant":          "#3b494b",
        "primary":                  "#dbfcff",
        "primary-container":        "#00f0ff",
        "primary-fixed":            "#7df4ff",
        "primary-fixed-dim":        "#00dbe9",
        "on-primary":               "#00363a",
        "on-primary-fixed":         "#002022",
        "on-primary-container":     "#006970",
        "inverse-primary":          "#006970",
        "secondary":                "#ffabf3",
        "secondary-container":      "#fe00fe",
        "secondary-fixed":          "#ffd7f5",
        "secondary-fixed-dim":      "#ffabf3",
        "on-secondary":             "#5b005b",
        "on-secondary-container":   "#500050",
        "tertiary-fixed-dim":       "#d1bcff",
        "tertiary-fixed":           "#e9ddff",
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "inverse-surface":          "#e4e1e9",
        "inverse-on-surface":       "#303036",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        "margin-desktop":  "40px",
        "margin-mobile":   "20px",
        "container-max":   "1200px",
        "gutter":          "16px",
        "unit":            "8px",
      },
      fontFamily: {
        "body-md":       ["Hanken Grotesk", "sans-serif"],
        "label-sm":      ["JetBrains Mono", "monospace"],
        "score-display": ["JetBrains Mono", "monospace"],
        "headline-md":   ["Sora", "sans-serif"],
        "display-lg":    ["Sora", "sans-serif"],
      },
      fontSize: {
        "body-md":      ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm":     ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "score-display":["20px", { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md":  ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg":   ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
};
